data_dir: '/Users/nikitazakharov/Desktop/deep_school/hw-01-modeling/archive'
name_model: 'resnet34'
batch_size: 128
test_size: 0.2
n_classes: 17
num_epochs: 25
seed: 42
step_size: 7
gamma: 0.1
beta: 2
threshold: .2
pretrained: True
criterion: 'torch.nn.BCEWithLogitsLoss'
criterion_kwargs: {}
encoder: 'sklearn.preprocessing.MultiLabelBinarizer'
encoder_kwargs: {}
optimizer: 'torch.optim.AdamW'
optimizer_kwargs:
  lr: 1e-4
  weight_decay: 1e-5
scheduler: 'torch.optim.lr_scheduler.StepLR'
scheduler_kwargs:
  step_size: 7
  gamma: 0.1
device: 'cpu'  # Set to "cuda:0" if available, otherwise "cpu"
